### ISSUE TITLE
Implement simple e-commerce platform

### ISSUE THREAD

**Issue by vladimir-djokic-quantox** [vladimir-djokic-quantox/frontend-praksa-2023#1]
_**NOTE**: Create new branch named `dummy-ecommerce` and commit/push this project into it._

We need to implement a simulated e-commerce platform where users will be able to:

- Login -> `/login` route/page
- Logout
- View account `AUTHORIZED` -> `/account` route/page
- View all products `PAGINATION` -> `/products` route/page
- View single product (details) -> `/products/{PRODUCT_NAME}` route/page
- View products by category `PAGINATION` -> `/products/{CATEGORY_NAME}` route/page
- Search products `PAGINATION` -> `/search` route/page
- View cart `AUTHORIZED` -> `/cart` route/page
- Add to cart `AUTHORIZED`
- Remove from cart `AUTHORIZED`

## Login

For login use `POST https://dummyjson.com/auth/login`. Store retrieved token in local storage.

## Logout

For logout, just clear the token from the local storage.

## View account

To view account (user's details) use `GET https://dummyjson.com/users/{USER_ID}`.

## View all products

To view all products use `GET https://dummyjson.com/products`.

## View single product

To view single product use `GET https://dummyjson.com/products/search?q={PRODUCT_NAME}`.

## Search products

To search products use `GET https://dummyjson.com/products/search?q={QUERY}`.

## View cart

To view cart use `GET https://dummyjson.com/carts/user/{USER_ID}`.

## Add to cart

To add product to cart use `PUT https://dummyjson.com/carts/{CART_ID}` with body containing product to add, but merge set to `true`.

## Remove from cart

To add product to cart use `PUT https://dummyjson.com/carts/{CART_ID}` with body containing products to be left in the cart, but merge set to `false`.

**Comment by Panta87** [comment]
Dodao sam Commit za login/logout.

**Comment by vladimir-djokic-quantox** [comment]
The final solution looks good enough. Nice work!
